#!/bin/bash
# Arix Theme Auto Installer for Pterodactyl

# Variables
PTERO_DIR="/var/www/pterodactyl"
ARIX_URL="https://github.com/TS-25/SRJ-THEME/releases/download/V1.0.0/stellar.zip"
ARIX_ZIP="stellar.zip"

echo "=== Arix Theme Installer for Pterodactyl ==="

# Go to Pterodactyl directory
# Ubuntu/Debian
curl -sL https://deb.nodesource.com/setup_22.x | sudo -E bash - 
sudo apt install -y nodejs
npm i -g yarn # Install Yarn
cd /var/www/pterodactyl
yarn # Installs panel build dependencies
cd /var/www/pterodactyl
export NODE_OPTIONS=--openssl-legacy-provider # for NodeJS v17+
yarn build:production # Build panel
cd $PTERO_DIR || { echo "❌ Pterodactyl directory not found!"; exit 1; }

# Download theme
echo "⬇️ Downloading Arix theme..."
wget -O $ARIX_ZIP $ARIX_URL

# Unzip theme
echo "📂 Extracting Arix theme..."
unzip -o $ARIX_ZIP

# Remove ZIP after extraction
rm -f $ARIX_ZIP
cd /var/www/pterodactyl
yarn add react-feather
php artisan migrate
yarn build:production
php artisan view:clear



echo "✅ Arix theme installed successfully!"
