#!/bin/bash


# build assets 
echo 'building assets'

curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt install -y nodejs
npm i -g yarn 
cd /var/www/pterodactyl
yarn
cd /var/www/pterodactyl
export NODE_OPTIONS=--openssl-legacy-provider
yarn build:production




