#!/bin/bash


# Before that, we need to clear up any existing files.
cd /var/www/reviactyl # Reviactyl installation path
rm -rf *

# Download file archive from GitHub
curl -Lo panel.tar.gz https://github.com/reviactyl/panel/releases/download/v2.1.2/panel.tar.gz

# Extract the archive
tar -xzvf panel.tar.gz
chmod -R 755 storage/* bootstrap/cache/
COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader
php artisan migrate --seed --force
chown -R www-data:www-data /var/www/reviactyl/*


# Use this command to set a $PTERODACTYL_DIRECTORY variable
# for use later in this guide.
export PTERODACTYL_DIRECTORY=/var/www/reviactyl

# Install curl, wget and unzip if you haven't already
sudo apt install -y curl wget unzip

# Navigate to your Reviactyl directory
cd $PTERODACTYL_DIRECTORY

# Download and unzip Blueprint's latest release
wget "$(curl -s https://api.github.com/repos/reviactyl/blueprint/releases/latest | grep 'browser_download_url' | grep 'release.zip' | cut -d '"' -f 4)" -O "$PTERODACTYL_DIRECTORY/release.zip"
unzip -o release.zip

# Install dependencies
sudo apt install -y ca-certificates curl git gnupg unzip wget zip

# Add Node.js apt repository
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
sudo apt update
sudo apt install -y nodejs

# cd into Pterodactyl, install yarn and node dependencies
cd $PTERODACTYL_DIRECTORY
npm i -g yarn
yarn install

# file making 
cat <<EOF > "$PTERODACTYL_DIRECTORY/.blueprintrc"
WEBUSER="www-data";
OWNERSHIP="www-data:www-data";
USERSHELL="/bin/bash";
EOF

# set permission 
chown -R www-data:www-data "$PTERODACTYL_DIRECTORY"

# Give blueprint.sh execute permissions
chmod +x $PTERODACTYL_DIRECTORY/blueprint.sh

# Run blueprint.sh
bash $PTERODACTYL_DIRECTORY/blueprint.sh
